spring.application.name=identity-service
api.security.token.secret=FJKVN:DJFN:VJDFNLKANDC{OIEJ{OIJNDVL:JLKNFVJBVJASS}POKQ}PDOK#}U{*({*##$@#@{OF{O!IN{OCNDLKVNOR
api.security.token.issuer=edifff.com
api.security.token.refresh-expiration=2
api.security.token.access-expiration=5


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.use-java-doc=true
springdoc.paths-to-match=/**

logging.level.root=INFO
logging.level.ru.rsreu.projectmanagment.identityservice=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

app.file.max-size-bytes=10485760