spring.application.name=identity-service
api.security.token.secret=FJKVN:DJFN:VJDFNLKANDC{OIEJ{OIJNDVL:JLKNFVJBVJASS}POKQ}PDOK#}U{*({*##$@#@{OF{O!IN{OCNDLKVNOR
api.security.token.isser=edifff.com
api.security.token.access-expiration=2
